apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: x2t01f1np-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0b883b8ab3.4qbp.p3.openshiftapps.com/rhtap/rhtap-qe:1688b14924be893bfbd83ad5fc9983e6564dd136@sha256:39d8c4e2486838394d2e00b135def5e2806dd629f5d319081a3483f669ece7ef
        name: container-image  
